version: '3.9'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: econempire
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build:
      context: ..
      dockerfile: docker/server.Dockerfile
    environment:
      NODE_ENV: production
      PORT: 4000
      FRONTEND_URL: http://localhost
      DATABASE_URL: postgres://postgres:postgres@db:5432/econempire
      JWT_SECRET: change-me-in-prod
    depends_on:
      - db
    ports:
      - "4000:4000"

  web:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
      args:
        REACT_APP_API_BASE: ""
        REACT_APP_SOCKET_URL: ""
    depends_on:
      - server
    ports:
      - "80:80"

volumes:
  db_data:
